### ISSUE TITLE
Paper: Removal of Gray Rubber Stamps

### ISSUE THREAD

**Issue by zhenzhenbadgirl** [soumyadeepdey/Gray-Rubber-Stamp-Removal#1]
Is this the source code implementation of that article? Removal of Gray Rubber Stamps. You are the author of this paper.

**Comment by soumyadeepdey** [comment]
Hi,
Sorry for the late reply. The version available in the GitHub is not the
exact version of the paper. There are slight variations from the original
code. The exact version of the code (paper) is actually part of a project,
and is not public due to copyright issues.
